### ISSUE TITLE
Use <i> instead of <img>

### ISSUE THREAD

**Issue by kordianbruck** [LeoColomb/flag-sprites#1]
Following the font-awesome and others, you might as well advertise the `<i>` tag on the website instead of including a `<img>` with a blank gif. Saves one additional request to the server and the css works just as fine with that.

**Comment by LeoColomb** [comment]
Thanks for your comment @kordianbruck, in fact it's not my website.
My repo is an improved source of the methodology, and http://flag-sprites.com is the direct inspiration.
Nevertheless, you can obviously prefer use the `<i>` tag in your code.
